import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

import { Providers } from "src/app/providers";
import { fonts } from "src/app/fonts";
// Providers added from https://chakra-ui.com/getting-started/nextjs-app-guide with Chakra UI

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blissful Cruises",
  description: "App generated by create next app presenting Blissful Cruises.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // The fonts className is unused but is here for further reference.
    <html lang="en" data-theme={"emerald"} className={fonts.rubik.variable}>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
